### ISSUE TITLE
udev规则不起作用

### ISSUE THREAD

**Issue by suiahae** [Kr328/clash-premium-installer#1]
安装脚本所设定的udev规则（[99-clash.rules](https://github.com/Kr328/clash-premium-installer/blob/master/scripts/99-clash.rules)）不起作用，需要手动执行`sudo /usr/lib/clash/setup-tun.sh`来配置tun。

**Comment by Benyjuice** [comment]
使用的什么系统，有可能系统的udev配置目录不是/usr/lib/udev
Ubuntu 18.04为/lib/udev

**Comment by suiahae** [comment]
> 使用的什么系统，有可能系统的udev配置目录不是/usr/lib/udev
> Ubuntu 18.04为/lib/udev

系统为 fedora32，我再尝试下。

**Comment by suiahae** [comment]
> 使用的什么系统，有可能系统的udev配置目录不是/usr/lib/udev
> Ubuntu 18.04为/lib/udev

Fedora 32 的 udev 配置目录为 /usr/lib/udev/rules.d。

在脚本中加入debug脚本后，发现udev规则可以生效，相应脚本“sudo /usr/lib/clash/setup-tun.sh”可以运行。但脚本对iptables的修改无效。

我另开一个issue吧
