### ISSUE TITLE
Tun下网速问题

### ISSUE THREAD

**Issue by lambdaplus** [Kr328/clash-premium-installer#22]
1、clash通过此脚本安装。
2、Clash宿主机为小米笔记本air  12.5，系统为deepin20.4
3、笔记本可以正常通过Tun上网。
4、我家移动宽带300M
问题描述：
1、安卓手机wifi设置为宿主机的ip和DNS,speed测速为9MB/s
2、还是安卓手机，DHCP，wifi代理设置成宿主机ip和7890端口号，测速为47-48MB/s
3、台式机win11按照上述两种方式设置，网速也是如上所述。

**Comment by lambdaplus** [comment]
``

**Comment by lambdaplus** [comment]
`dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114 # 真实请求DNS，可多设置几个
tun:
  enable: true
  stack: system # 或 gvisor
  dns-hijack:
    - 1.0.0.1:53 # 请勿更改`

**Comment by lambdaplus** [comment]
> dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114 # 真实请求DNS，可多设置几个
tun:
  enable: true
  stack: system # 或 gvisor
  dns-hijack:
    - 1.0.0.1:53 # 请勿更改

**Comment by lambdaplus** [comment]
` dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114 # 真实请求DNS，可多设置几个
tun:
  enable: true
  stack: system # 或 gvisor
  dns-hijack:
    - 1.0.0.1:53 # 请勿更改 `

**Comment by lambdaplus** [comment]
> dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114 # 真实请求DNS，可多设置几个
tun:
  enable: true
  stack: system # 或 gvisor
  dns-hijack:
    - 1.0.0.1:53 # 请勿更改

**Comment by lambdaplus** [comment]
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114 # 真实请求DNS，可多设置几个
tun:
  enable: true
  stack: system # 或 gvisor
  dns-hijack:
    - 1.0.0.1:53 # 请勿更改

**Comment by a1mersnow** [comment]
what's the difference between using dns-hijack and redirecting to clash's dns listening port?

**Comment by lambdaplus** [comment]
应该是我自己电脑或者网络问题，打扰了，抱歉。
