### ISSUE TITLE
docker环境下的op权限受限，还有其它方法安装么

### ISSUE THREAD

**Issue by matthuo333** [Kr328/clash-premium-installer#3]
~/clash-premium-installer# ./installer.sh install
-ash: ./installer.sh: Permission denied

**Comment by matthuo333** [comment]
给对象增加权限后，又提示，install 找不到。。。

**Comment by Kr328** [comment]
openwrt 没有 systemd 和 udev

从根本上不能使用这个脚本

至于其他方法 大概只有 openclash 了吧

**Comment by matthuo333** [comment]
由于docker op中 openclash配置后不出海，分析后或是iptables mangle表设置不对，Dreamacro 大神推荐参考你这个项目。
如果从openclash安装，是从哪里装？或者仅是配置 setup-tun.sh 该怎么做？

**Comment by Kr328** [comment]
参考我这个为桌面发行版设计的脚本 对 openwrt 没有任何用处

以及 openwrt 我也不了解 这种东西自己想办法解决吧

**Comment by matthuo333** [comment]
你这个为发行版的宿主与其docker环境配合出的脚本么？

**Comment by Kr328** [comment]
有无 docker 不在这个脚本的考虑范围之内

脚本是为 **桌面发行版** 设计

也就是平时在 Linux 使用图形界面的人
