### ISSUE TITLE
安装提示“cgroup not support net_cls”及处理措施

### ISSUE THREAD

**Issue by luwah** [Kr328/clash-premium-installer#5]
`sudo ./installer.sh install`
提示`cgroup not support net_cls`
于是`mkdir -p /sys/fs/cgroup/net_cls`后安装完成

启动后报错
` /sys/fs/cgroup/net_cls/bypass_proxy/net_cls.classid permission denied`
`/sys/fs/cgroup/net_cls/bypass_proxy/tasks no such file or directory`

于是参考[net_cls](https://www.kernel.org/doc/Documentation/cgroup-v1/net_cls.txt)编辑setup-cgroup.sh如下

```
if [ ! -d "/sys/fs/cgroup/net_cls" ];then
	mkdir -p /sys/fs/cgroup/net_cls
	exit 0
fi
mount -t cgroup -onet_cls net_cls /sys/fs/cgroup/net_cls
mkdir -p /sys/fs/cgroup/net_cls/bypass_proxy
echo "$PROXY_BYPASS_CGROUP" > /sys/fs/cgroup/net_cls/bypass_proxy/net_cls.classid
chmod 666 /sys/fs/cgroup/net_cls/bypass_proxy/tasks
```
目前本机运行无报错，可顺利开启tun。
注：本机Debian bullseye版本，本人是普通用户，对代码编辑了解少，如有差错请多包涵。
最后感谢作者提供该脚本工具为普通用户一键开启tun模式，不知道后期是否会编写一键开启tproxy模式。

**Comment by Kr328** [comment]
试试新的提交

**Comment by luwah** [comment]
可以顺利安装，谢谢
